blank_issues_enabled: false
contact_links:
  - name: ğŸ”— Houdoku repository
    url: https://github.com/xgi/houdoku/issues/new/choose
    about: Reports/requests for Houdoku itself should be opened in the main repository
  - name: ğŸ–¥ï¸ Houdoku website
    url: https://houdoku.org
    about: Documentation for using Houdoku
